version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloWorldPython"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uo9ed0weh0s6"
s3_prefix = "helloWorldPython"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=343924329623.dkr.ecr.us-east-1.amazonaws.com/helloworldpython22d36c06/helloworldfunction19d43fc4repo"]
